.test_template: &job_definition
  stage: test
  image: docker:stable
  services:
    - docker:dind
  script:
    # get test image
    - docker pull $IMAGE_PATH
    - docker tag $IMAGE_PATH test_image
    # install docker compose
    - apk add --update python py-pip python-dev && pip install --quiet docker-compose~=1.23.0
    - docker-compose version
    # create custom composer file
    - python Resources/gitlab_ci/create_composer.py $SYMFONY_VERSION
    # start containers
    - docker-compose -f Resources/gitlab_ci/docker-compose.test.yml up -d
    # init
    - docker exec -w /code -e COMPOSER=custom_composer.json php_test_image composer install --prefer-dist --no-suggest --no-progress
    # testing
    - docker exec -w /code php_test_image php vendor/bin/phpunit
    # stopping container
    - docker-compose -f Resources/gitlab_ci/docker-compose.test.yml down
  tags:
    - docker

image: docker:stable

services:
  - docker:dind

variables:
  CONTAINER_IMAGE: registry.gitlab.com/$CI_PROJECT_PATH
  DOCKER_DRIVER: overlay2

before_script:
  - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN registry.gitlab.com
  - docker version

stages:
  - build
  - test

build:php72:
  stage: build
  image: docker:stable
  services:
    - docker:dind
  variables:
    IMAGE_PATH: $CI_REGISTRY_IMAGE:php72
  script:
    # build test image
    - sh Resources/gitlab_ci/pull_cache.sh "$CI_COMMIT_MESSAGE" "$IMAGE_PATH"
    - docker build --build-arg PHP_VERSION=php:7.2-fpm  --cache-from $IMAGE_PATH --tag $IMAGE_PATH --tag php72 -f ./Resources/gitlab_ci/Dockerfile .
    - docker push $IMAGE_PATH
  tags:
    - docker

build:php73:
  stage: build
  image: docker:stable
  services:
    - docker:dind
  variables:
    IMAGE_PATH: $CI_REGISTRY_IMAGE:php73
  script:
    # build test image
    - sh Resources/gitlab_ci/pull_cache.sh "$CI_COMMIT_MESSAGE" "$IMAGE_PATH"
    - docker build --build-arg PHP_VERSION=php:7.3-fpm  --cache-from $IMAGE_PATH --tag $IMAGE_PATH --tag php73 -f ./Resources/gitlab_ci/Dockerfile .
    - docker push $IMAGE_PATH
  tags:
    - docker

test:php72_s34:
  <<: *job_definition
  variables:
    IMAGE_PATH: $CI_REGISTRY_IMAGE:php72
    SYMFONY_VERSION: 3.4.*

test:php72_s40:
  <<: *job_definition
  variables:
    IMAGE_PATH: $CI_REGISTRY_IMAGE:php72
    SYMFONY_VERSION: 4.0.*

test:php72_s41:
  <<: *job_definition
  variables:
    IMAGE_PATH: $CI_REGISTRY_IMAGE:php72
    SYMFONY_VERSION: 4.1.*

test:php72_s42:
  <<: *job_definition
  variables:
    IMAGE_PATH: $CI_REGISTRY_IMAGE:php72
    SYMFONY_VERSION: 4.2.*

test:php72_s43:
  <<: *job_definition
  variables:
    IMAGE_PATH: $CI_REGISTRY_IMAGE:php72
    SYMFONY_VERSION: 4.3.*

test:php73_s34:
  <<: *job_definition
  variables:
    IMAGE_PATH: $CI_REGISTRY_IMAGE:php73
    SYMFONY_VERSION: 3.4.*

test:php73_s40:
  <<: *job_definition
  variables:
    IMAGE_PATH: $CI_REGISTRY_IMAGE:php73
    SYMFONY_VERSION: 4.0.*

test:php73_s41:
  <<: *job_definition
  variables:
    IMAGE_PATH: $CI_REGISTRY_IMAGE:php73
    SYMFONY_VERSION: 4.1.*

test:php73_s42:
  <<: *job_definition
  variables:
    IMAGE_PATH: $CI_REGISTRY_IMAGE:php73
    SYMFONY_VERSION: 4.2.*

test:php73_s43:
  <<: *job_definition
  variables:
    IMAGE_PATH: $CI_REGISTRY_IMAGE:php73
    SYMFONY_VERSION: 4.3.*

test:php73_laters:
  stage: test
  image: docker:stable
  services:
    - docker:dind
  variables:
    IMAGE_PATH: $CI_REGISTRY_IMAGE:php73
  script:
    # get test image
    - docker pull $IMAGE_PATH
    - docker tag $IMAGE_PATH test_image
    # install docker compose
    - apk add --update python py-pip python-dev && pip install --quiet docker-compose~=1.23.0
    - docker-compose version
    # start containers
    - docker-compose -f Resources/gitlab_ci/docker-compose.test.yml up -d
    # init
    - docker exec -w /code php_test_image composer install --prefer-dist --no-suggest --no-progress
    # testing
    - docker exec -w /code php_test_image php vendor/bin/phpunit
    # stopping container
    - docker-compose -f Resources/gitlab_ci/docker-compose.test.yml down
  tags:
    - docker
  artifacts:
    paths:
      - var/phpunit
    expire_in: 2 days